import type { Metadata } from "next";
import Image from "next/image";
import QRCode from "qrcode";
import { DownloadTracker } from "@/components/download/DownloadTracker";
import { PlatformIcon } from "@/components/download/StoreBadge";
import { downloads } from "@/config/downloads";
import { site } from "@/config/site";
import { TrackedAnchor } from "@/components/ui/TrackedAnchor";
import type { Goal } from "@/lib/analytics";
export const metadata: Metadata = { title: "Скачать Joobby для iPhone, Android и компьютера", description: "Установите приложение Joobby или откройте веб-версию. Все способы установки на одной странице." };
export default async function DownloadPage() {
    const qr = { appStore: await QRCode.toDataURL(downloads.appStore.url, { margin: 1, width: 220 }), googlePlay: await QRCode.toDataURL(downloads.googlePlay.url, { margin: 1, width: 220 }) };
    const cards = [{ key: "app_store", goal: "download_app_store_click" as Goal, icon: "apple", title: "iPhone и iPad", text: downloads.appStore.requirement, url: downloads.appStore.url, label: "Открыть App Store", qr: qr.appStore }, { key: "google_play", goal: "download_google_play_click" as Goal, icon: "googlePlay", title: "Android", text: downloads.googlePlay.requirement, url: downloads.googlePlay.url, label: "Открыть Google Play", qr: qr.googlePlay }, { key: "apk", goal: "download_apk_click" as Goal, icon: "android", title: "Установить APK", text: "Если Google Play недоступен. Прямая загрузка с сайта Joobby.", url: downloads.apk.url, label: "Скачать APK" }, { key: "web_app", goal: "download_web_app_click" as Goal, icon: "web", title: "На компьютере", text: "Откройте Joobby в браузере. Установка не нужна.", url: downloads.web.url, label: "Открыть веб-версию" }] as const;
    return <div className="download-page"><DownloadTracker /><section className="download-intro"><div><p className="eyebrow">Приложения Joobby</p><h1>Ваша смена.<br />На вашем устройстве.</h1><p>Выберите способ установки. Если вас пригласили в команду, войдите с почтой из приглашения.</p></div><span>На компьютере? Отсканируйте QR-код камерой телефона.</span></section><section className="section-tight download-platforms" aria-label="Способы установки"><div className="container platform-grid">{cards.map(card => <article className="platform-card" data-platform={card.key} key={card.key}><div><span className="platform-icon" aria-hidden="true"><PlatformIcon kind={card.icon} /></span><h2>{card.title}</h2><p>{card.text}</p><TrackedAnchor className="button" href={card.url} target="_blank" rel="noopener noreferrer" goal={card.goal}>{card.label}</TrackedAnchor>{card.key === "apk" && <details className="apk-steps"><summary>Как установить APK</summary><ol><li>Скачайте файл с joobby.ru.</li><li>Если Android запросит разрешение, разрешите установку для браузера, которым скачали файл.</li><li>Установите Joobby. После установки разрешение можно отключить.</li></ol></details>}</div>{"qr" in card && card.qr && <Image className="qr" src={card.qr} width={96} height={96} unoptimized alt={`QR-код: ${card.label}`}/>}</article>)}</div><div className="container download-help"><p>Не получилось установить или войти?</p><a href={`mailto:${site.email}`}>Написать в поддержку ↗</a></div></section><section className="section-tight"><div className="container"><div className="content-card"><p className="eyebrow">Уже есть приглашение?</p><h2>Установите. Войдите. Вы в команде.</h2><p className="lead">Используйте адрес, на который пришло приглашение. Приложение отправит одноразовый код для входа — постоянный пароль не нужен.</p></div></div></section></div>;
}
